### ISSUE TITLE
Connection Not Private Message - URL link in notification text messages

### ISSUE THREAD

**Issue by skadev1** [judsonmusic/sk4#148]
Users that click on the link (https://www.skoolaide.com) that’s embedded in the text notification, the user is directed to this link that references a security risk.

![skoolaide url security risk](https://user-images.githubusercontent.com/18357094/36082988-64849066-0f7c-11e8-923f-10d6bec43f2a.jpg)

**Comment by judsonmusic** [comment]
There is a problem with the certificate, I will call COMODO on this one tomorrow sometime.

**Comment by skadev1** [comment]
![skoolaide url security risk](https://user-images.githubusercontent.com/18357094/36086190-c5d1b54e-0f98-11e8-9e7e-0739d182b435.jpg)
Additional broken paths discovered.
If I access links that's referenced in the text notifications I encounter...
1) the url links are not consistent across notifications.  One notification will show: https://www.skoolaide.com and another notification will show: www.skoolaide.com 
2) both links (on a J3 Samsung Android 6.01 resolves to blank page when attempted to open on phone browser.
3) links in notifications resolve to certification error when used in J7 Samsung Android 7.0

![20180212_004155](https://user-images.githubusercontent.com/18357094/36086133-7291b6c2-0f98-11e8-8bab-383ab5c948f0.jpg)
![20180212_004514](https://user-images.githubusercontent.com/18357094/36086134-72ae4102-0f98-11e8-99c0-920ff86f3e72.jpg)
