### ISSUE TITLE
Low Priority - Cell Phone Numbers show up duplicated in advocate references under primary parent's panel

### ISSUE THREAD

**Issue by skadev1** [judsonmusic/sk4#149]
Need to check db and see if there are holdover tags for cell phone number 704-577-4392 in demo users' profiles.  The following snap shot shows that the referenced cell number is listed under two non-primary advocates' info panel that are listed under the primary parent's panel.  It's possible the 4392 number was part of these demo user's profiles before they were recently deleted.   I've confirmed that this number is not currently listed in either non-primary advocate's profile.

IF the references can't be found, then it may mean that all non-primary advocates linked to a student have somehow been linked to the student's cell number.

![Cell Number Holdovers.JPG](https://images.zenhubusercontent.com/594bd93351aa2c3057828382/dde446db-6dd1-4514-8a22-053e58806456)

**Comment by skadev1** [comment]
This will need to be fixed at some point due to reason Judson noted.  'If a user changes their phone number or email, the old data will continue to be reflected in the db.'  

Per Judson - "It's a complicated issue because the process is utilizing the phone number that was originally entered into the system when the connection between users was requested.  I will have to write a new algorithm to mix the actual account information that is up to date with the original connection information."

**Comment by judsonmusic** [comment]
@skadev1 , this is fixed. I fixed it this morning.
